spring.application.name=demo
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=springb1434@gmail.com
spring.mail.password=xrch uvfs hjbo croi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true